### ISSUE TITLE
App crashes at out of memory error

### ISSUE THREAD

**Issue by NamanRawat1** [Sapnethedreams/Sapne#11]
Screenshot:
![screenshot_2017-10-05-18-09-23-267_com miui bugreport](https://user-images.githubusercontent.com/21363531/31325466-2e38308e-acdb-11e7-9a5b-90efeca80bfa.jpg)
Work on this issue:
Anyone can work on this issue.

**Comment by prachibanik** [comment]
On opening which page/activity did the app crash? Also let me know your phone model so that I can work using a similar environment
